/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author oVTuan
 */
public final class Stage extends javax.swing.JFrame implements ActionListener {

   JPanel pane = new JPanel();
    int count = 0;
    ArrayList<ButtonPlz> listXxX; 

    /**
     * Creates new form Stage
     */
    public Stage() {
        initComponents();
        initXxX(3);
    }

    public void initXxX(int x) {
        count = 0;
        lbcount.setText("0");
        listXxX = new ArrayList<>();
        pane.setLayout(new GridLayout(x, x));
        pane.setSize(300,300);

        ArrayList<Integer> randomlist = new ArrayList<>();
        for (int i = 0; i < x * x; i++) {
            randomlist.add(i);
        }
        Collections.shuffle(randomlist);
        for (int i = 0; i < x * x; i++) {
            String text = randomlist.get(i).toString();
            if (text.equals("0")) {
                text = "";
            }
            ButtonPlz bPlz = new ButtonPlz(i, x, text);
            bPlz.addActionListener(this);
            listXxX.add(bPlz);
        }
        squaretify(x);
        for (int i = 0; i < x * x; i++) {
            pane.add(listXxX.get(i));
        }
        this.add(pane);
    }

    public void squaretify(int x) {
        //cat tren
        for (int i = 0; i < x; i++) {
            listXxX.get(i).removeASwapAble(-x);
        }
        //cat duoi
        for (int i = x * x - x; i < x * x; i++) {
            listXxX.get(i).removeASwapAble(x);
        }
        //cat trai
        for (int i = 0; i <= x * x - x; i += x) {
            listXxX.get(i).removeASwapAble(-1);
        }
        //cat phai
        for (int i = x - 1; i < x * x; i += x) {
            listXxX.get(i).removeASwapAble(1);
        }
    }

    public void swapButton(ButtonPlz src, ButtonPlz des) {
        des.setText(src.getText());
        src.setText("");
        lbcount.setText(Integer.toString(count+=1));
    }

    public boolean checkWin() {
        for (int i = 0; i < pane.getComponentCount() - 1; i++) {
            int x = 0;
            String s = ((ButtonPlz) pane.getComponent(i)).getText();
            if (!s.equals("")) {
                x = Integer.parseInt(s);
            }
            if (x != (i + 1)) {
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewGame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chooseSize = new javax.swing.JComboBox<>();
        lbcount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNewGame.setText("New Game");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        jLabel1.setText("Size:");

        jLabel2.setText("Moves:");

        chooseSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3x3", "4x4" }));
        chooseSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseSizeActionPerformed(evt);
            }
        });

        lbcount.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNewGame)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chooseSize, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcount))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chooseSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbcount))
                .addGap(28, 28, 28)
                .addComponent(btnNewGame)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        // TODO add your handling code here:
        String s = chooseSize.getSelectedItem().toString();
        pane.removeAll();
        initXxX(Integer.parseInt(s.substring(0, 1)));
        pane.revalidate();
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void chooseSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseSizeActionPerformed
        // TODO add your handling code here:
        String s = chooseSize.getSelectedItem().toString();
        pane.removeAll();
        initXxX(Integer.parseInt(s.substring(0, 1)));
        pane.revalidate();
    }//GEN-LAST:event_chooseSizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stage().setVisible(true);
            }
        });
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        ButtonPlz b = (ButtonPlz) ae.getSource();
        for (Integer swapAble : b.getSwapAble()) {
            ButtonPlz bDes = (ButtonPlz) pane.getComponent(swapAble);
            if (bDes.getText().equals("")) {
                swapButton(b, bDes);
            }
        }
        System.out.println(checkWin());
         if (checkWin()) {
                //show message winner
                int x = JOptionPane.showConfirmDialog(this, "You win, New game?", "Congratulation", JOptionPane.YES_OPTION);
                if (x == JOptionPane.YES_OPTION) {
                    btnNewGameActionPerformed(ae);
                }
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewGame;
    private javax.swing.JComboBox<String> chooseSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbcount;
    // End of variables declaration//GEN-END:variables
}
